### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by mrosama** [hypery2k/cordova-email-plugin#11]
first > **how can configured email account tto  send emails**
- email not send. no alert no dismissed show  i dont know why?

cordova.plugins.email.open({
    to:['osama_eg@live.com'], // email addresses for TO field
    subject:"hi" , // subject of the email
    body:"test...", // email body (for HTML, set isHtml to true)
    isHtml:true, // indicats if the body is HTML or plain text
}, function(){
alert('email view dismissed');
}, this);
## }

i test on real device

**Comment by hypery2k** [comment]
on which device with which cordova version?

**Comment by hypery2k** [comment]
Without any hints what version and platform you're using I cannot help you

**Comment by hypery2k** [comment]
closed due to no response
