### ISSUE TITLE
PDF/png attachments with Gmail

### ISSUE THREAD

**Issue by Vurk** [hypery2k/cordova-email-plugin#15]
Hi, I´m trying to send an email with a pdf attachment on Android 5.1.1 with Gmail but it doesn't work. Gmail tells me it cannot attach an empty file so I trying with a simple png. This is the code I´m using:

let filename = 'icon.png';
let img64 = 'iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAA...'
let email = {
  to: 'To email',  
  attachments: [
    'base64:' + filename + '//' + img64,
  ],
  subject: 'Subject',
  isHtml: true
};
cordova.plugins.email.open(email);

The code opens Gmail correctly and fills all the fields, but it prompts a message telling me that it can not attach an empty file.

I don´t want the app saves the file into the device storage. I´m missing something?

Thanks in advance.
##

**Comment by hypery2k** [comment]
You can try to use the development version (nightly build), which maybe **not stable!**:

```
cordova plugin add cordova-plugin-email@next
```

**Comment by hypery2k** [comment]
closed due to no response

**Comment by paduchurikowsik** [comment]
Hello,
i am having the same issue. I am using ionic framework.when i try to attach an image from cordova camera plugin photo library in android i get the same error
