### ISSUE TITLE
mimeType must not be nil.

### ISSUE THREAD

**Issue by edwardcrane** [hypery2k/cordova-email-plugin#16]
Plugin 1.1.0, ios 9.3.2.

Works fine on Android, but on iOS my app simply crashes. I debug it in XCode and get the following error:

**\* Assertion failure in - [MFMailComposeInternalViewController addAttachmentData:mimeType:fileName:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/MessageUI/MessageUI-1637.33/Mail/MFMailComposeInternalViewController.m:746
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[MFMailComposeInternalViewController addAttachmentData:mimeType:fileName:] mimeType must not be nil.'.

Is there a way to set a mimeType in this Plugin?  I tried pre-pending "application/octet-stream:" to the filename, but that just crashed with an exception about the file being nil.

Please help.

Thanks,
Edward

**Comment by edwardcrane** [comment]
I think I have fixed it in my local XCode build.  Sadly, I am ignorant about contributing my change to your codebase.  I will happily do so, and view this as an opportunity to learn the process.  However, I just want to get the information posted along with the bug in case anyone else is looking at it.  I will try to contribute fix tomorrow.

So, in APPEmailComposer.m, in the setAttachments method, I check mimeType for nil after getMimeTypeFromFileExtension.  if it is nil, then i set it to @"application/octet-stream".

Thank you for your excellent plugin!  I will research the contribution process and try to contribute tomorrow.

Thank you,

Edward

**Comment by hypery2k** [comment]
thanks, Edward. Looking forward for your pull request

**Comment by edwardcrane** [comment]
OK, I have submitted pull request with fix.  I apologize for my ignorance in this process.  If there are any problems with it, I will be back in the office this evening after a conference.

Thank you,

Edward

**Comment by hypery2k** [comment]
looks good so far.

Thanks.

**Comment by hypery2k** [comment]
I've created a bugfix release 1.1.1

Don't find currently time for working on 1.2.0
