### ISSUE TITLE
Unable to attach file due to IO error

### ISSUE THREAD

**Issue by rolinger** [hypery2k/cordova-email-plugin#18]
The plugin is asking user to select email app to use.  For my test I am using Outlook email App.   It opens the app, populates the TO, Subject and Msg of the body just fine, but then I get a specific error:

`Unable to add attachment due to IO error`

I am attaching the file as such, the userdata.json file does exist (as its created upon app start up and I can read/write back into it during the app usage. 

'cordova.file.dataDirectory = file:///data/data/com.ionicframework.myApp/files/'

>   cordova.plugins.email.open({
>     to: ["blahblah@gmail.com"],
>     subject: title + " : " +sub,
>     body : msg,
>     attachments: cordova.file.dataDirectory + "userdata.json",
>     isHtml: 0,
>   }, function(){ console.log("Email cancelled")},
>     this
>   ) ;
##

**Comment by hypery2k** [comment]
Please give more details about your setup? What OS, what version of OS, which cordova version ...?
Some more information is needed ...

**Comment by rolinger** [comment]
Sorry about that should have included that in for the first time. I am using ionic  1.8 over Cordova 6.0 on Android platform. Do you need any other information?

**Comment by hypery2k** [comment]
which android version? There is no Ionic 1.8 version. Are using an Ionic 2 beta version?

**Comment by rolinger** [comment]
Ionic  1.7.14 and Android 5.1.1

**Comment by rolinger** [comment]
Ionic 1.78 and Android 5.

**Comment by rolinger** [comment]
Android 5.1.1

**Comment by hypery2k** [comment]
so you're using ionic-cli 1.7?

**Comment by hypery2k** [comment]
you have to resolve the file path:

```
window.resolveLocalFileSystemURL(cordova.file.dataDirectory, function (dirEntry) {
    console.log('file system open: ' + dirEntry.name);
}, onErrorLoadFs);
```

see https://github.com/apache/cordova-plugin-file#append-a-file-using-alternative-methods-

**Comment by rolinger** [comment]
I got a step further but still getting the same IO Outlook error.  I also tried with Gmail and the error message was: "Permission denied for the attachment"

According to the cordova-plugin-file docs, 'dataDirectory' is a read/write directory.

```
>   window.resolveLocalFileSystemURL(cordova.file.dataDirectory, function (dirEntry) {
>     var nativePath = dirEntry.toURL() ;
>     console.log('file system open: ' + nativePath);
>     // prints out: file:///data/data/com.ionicframework.myApp/files/
>     cordova.plugins.email.open({
>       to: ['blahblah@gmail.com'],
>       subject: title + ' : ' +sub,
>       body : msg,
>       attachments: nativePath + 'userdata.json',
>       isHtml: 0,
>     }, function(){ console.log('Email cancelled')},
>       this
>     ) ;
>   }, function() {console.log('Failed to resolve filePath'); 
>   });
```

**Comment by hypery2k** [comment]
did you request the permissions to file storage within your app?

**Comment by rolinger** [comment]
I am reading into it more, but the userdata.json file it is created and/or written to upon app start up.  That function doesn't have any file permissions set and yet it is successfully writing to the file - thus I would think that the app and file locations already have correct permissions to be able to read/file attach later.

**Comment by hypery2k** [comment]
try to read the file:

```
function readFile(fileEntry) {

    fileEntry.file(function (file) {
        var reader = new FileReader();

        reader.onloadend = function() {
            console.log("Successful file read: " + this.result);
            displayFileData(fileEntry.fullPath + ": " + this.result);
        };

        reader.readAsText(file);

    }, onErrorReadFile);
}
```

**Comment by rolinger** [comment]
I never got this working but came up with a different solution, simply just read in the attachment as an object and pasted that to the body of the message.  Go ahead and close this out, I am certain its something on my end but could never see what it was.  My other solution actually played out better (for now) as I am able to use it in other areas too.  Will probably have to come back to this one later.

**Comment by hypery2k** [comment]
You can try to use the development version (nightly build), which maybe **not stable!**:

```
cordova plugin add cordova-plugin-email@next
```
