### ISSUE TITLE
Unable to open email composer in device. 

### ISSUE THREAD

**Issue by bandhavya** [hypery2k/cordova-email-plugin#21]
isAvailable is false. But I have Gmail app in device.
email.open is not working 

In iOS, im unable to open composer. How to resolve in iOS ?
What does urischema mean ?

**Comment by hypery2k** [comment]
Can you share the code you're using and any logs? Also need information about device and cordova version you're using

**Comment by bandhavya** [comment]
cordova version is 6.0.0. I tried in both android 5.1.0 and android 6 version. 

My code inside document.ready is

var emailComposer = cordova.plugins.email;

```
    cordova.plugins.email.isAvailable(
        function(isAvailable) {
            alert('Service is not available' + isAvailable); // this alerts pops up.
        }
    );


    cordova.plugins.email.open({
        to: 'bandhavya9@gmail.com',
        cc: 'bandhavya9@gmail.com',
        bcc: ['bandhavya9@gmail.com'],
        subject: 'Greetings',
        body: 'How are you? Nice greetings from Cordova'
    }, function () {
       alert('email view dismissed');
    }, this);
```

email.open is neither returning a email draft nor alert saying email view dismissed.

**Comment by bandhavya** [comment]
i'm supposed to include app: 'gmail' in options. It works now.

**Comment by bandhavya** [comment]
Direct send option is not available ? When i open it navigates to gmail app and then sends the email on click of send. Is it possible to send directly

**Comment by bandhavya** [comment]
Is it mandatory to use the property "app" ?? Without using "app" I cannot send the mail ?
I have issue in iOS with the same code mentioned above

What should be given in urischema?

cordova.plugins.email.isAvailable(
    urischeme, function (isAvailable, withScheme) {
        // alert('Service is not available') unless isAvailable;
    }
);

**Comment by hypery2k** [comment]
did you use it after device ready event? which version of the plugin are you using?

**Comment by hypery2k** [comment]
as it's mentioned in the docs you must: https://github.com/hypery2k/cordova-email-plugin#specify-email-app
