### ISSUE TITLE
Crash when checking availability

### ISSUE THREAD

**Issue by ohh2ahh** [hypery2k/cordova-email-plugin#23]
The plugin crashes with the following error when it checks for the availability (see screenshot).

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x1890821c0 0x187abc55c 0x188f5e4ac 0x1001916dc 0x10034925c 0x10034921c 0x1003572d4 0x100358e6c 0x100358bb8 0x1881162b8 0x188115da4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

![screenshot](https://cloud.githubusercontent.com/assets/2352329/20039937/d8838cc4-a44d-11e6-9561-257517e33dbe.png)

I'm using the plugin in combination with Ionic 2 RC.2 and [Ionic Native](https://ionicframework.com/docs/v2/native/email-composer/). The app is running on a real device with iOS 10.1.1.

My code:
```
    let address: string = '...';
    let subject: string = '...';
    
    EmailComposer.isAvailable().then((available: boolean) => {
      if(available) {
        let email = {
          to: address,
          subject: subject,
          isHtml: false
        };

        EmailComposer.open(email);
      }
      else {
        // Fallback
      }
    });
```

```
System information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: Mac OS X Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by hypery2k** [comment]
thanks for reporting the issue, new version 1.2.1 is available

**Comment by ohh2ahh** [comment]
Thank you very much for your ultra fast fix!

Unfortunately `EmailComposer.isAvailable()` is returning now always `false` and I don't know if this is related to the previous bug. There is of course an email account installed on the iOS Mail.app. Maybe this console log from Xcode helps: `[MC] Filtering mail sheet accounts for bundle ID: <myAppID>, source account management: 1`

I'm using the latest version 1.2.1 and I already removed and re-added the iOS platform. The code is the same as above. Thanks again for your patience :)

**Comment by hypery2k** [comment]
does it working with 1.2.2?

**Comment by ohh2ahh** [comment]
Yes, thank you for your effort! Although it works only with plain JavaScript and not with Ionic Native and TypeScript. I suppose it's an issue with the [plugin implementation in Ionic Native](http://ionicframework.com/docs/v2/native/email-composer/).
