### ISSUE TITLE
isAvailable is always false on iOS 10

### ISSUE THREAD

**Issue by wintersieck** [hypery2k/cordova-email-plugin#25]
Testing on an actual iPad with iOS 10.0.2 and an email client configured (Google Inbox), and isAvailable is always false.

Ignoring that and attempting to use "cordova.plugins.email.open" anyway doesn't do anything.

Thanks!

**Comment by wintersieck** [comment]
Just noticed that this is a duplicate of the new development of #23. Leaving open for now, feel free to close if that issue covers this.

**Comment by hypery2k** [comment]
does it working with 1.2.2?

**Comment by requenaxii** [comment]
Hi, current version with last commits works fine for my in iOS 10.1 and Android. Thanks!

**Comment by hypery2k** [comment]
could you try with `cordova plugin add cordova-plugin-email@next`?

**Comment by hypery2k** [comment]
verified for me with iOS 10.1
