### ISSUE TITLE
Android: cordova.plugins.email.isAvailable always false

### ISSUE THREAD

**Issue by vespino** [hypery2k/cordova-email-plugin#29]
I have updated the plugin to v 1.2.1 for a project and it seems like cordova.plugins.email.isAvailable always returns false. I do have a mail app installed and setup. The app is called "boxer" which seems to be the default mail client on Cyanogen 13.1.2 which I'm using. I'm using the following code:

	cordova.plugins.email.isAvailable(
		function(isAvailable) {
			if(isAvailable) {
				//do something with cordova.plugins.email.open				
			}else{
				//alert no email available				
			}
		}
	);

Could this be related to the issue #23 and #25 ?

**Comment by vespino** [comment]
Problem seems to begin with v 1.2.0, no problem using v 1.1.1.

**Comment by hypery2k** [comment]
does it working with 1.2.2?

**Comment by vespino** [comment]
@hypery2k nope.

**Comment by IamAdamJowett** [comment]
@hypery2k can only confirm what @vespino is saying, always false in 1.2.1 and 1.2.2

**Comment by hypery2k** [comment]
Are you using plain JavaScript or TypeScript?

**Comment by vespino** [comment]
I'm using JavaScript.

**Comment by IamAdamJowett** [comment]
Javascript here as well

**Comment by panduit-psh** [comment]
I am using Ionic 2 with Typescript and isAvailable() is erroring on both Android and iOS, not even running the "then" script.

Edit: Also, open() does nothing on Android. Downgrading to 1.1.1 fixes it.

**Comment by vespino** [comment]
@hypery2k any news on this or should I keep using the old version?

**Comment by hypery2k** [comment]
could you try with `cordova plugin add cordova-plugin-email@next`?

**Comment by vespino** [comment]
How do I do that? I'm using PGB, only using NPM plugins.

**Comment by hypery2k** [comment]
try using version **1.2.2-22**

**Comment by vespino** [comment]
@hypery2k same ol', same ol' ... so still doesn't work. But NPM seems to have version 1.2.2.

**Comment by vespino** [comment]
Why is this closed? Problem still exists.

**Comment by hypery2k** [comment]
Should work with 1.2.3

**Comment by vespino** [comment]
I confirm! Thanks.

**Comment by vespino** [comment]
"There is one more thing": my app is in Dutch, the popup that appears on Android asking which app to use is English where other plugins (like https://www.npmjs.com/package/cordova-plugin-x-socialsharing) are in the set language.

**Comment by hypery2k** [comment]
I've created a new issue for that: #37

**Comment by waybackrider** [comment]
hi,

just created an new cordova Project using this plugin and isAvailable alwas return an empty string, instead of a bool.
Using latest Cordova (6.4.0) and latest Android Platform (6.1.0) and tested on CM 13 and Stock Android 4.4, same Result, can this be confirmed?

thx

**Comment by adamduren** [comment]
I tried `1.2.3` and I am still getting that there is no email client available. 
Edit: I get an empty string. Same as above.
