### ISSUE TITLE
isAvailable does not call callback on unsupported platform

### ISSUE THREAD

**Issue by resident-uhlig** [hypery2k/cordova-email-plugin#3]
`cordova.plugins.email.isAvailable(foo)` never calls `foo` on an unsupported platfrom (e.g. browser). I suggest to call the callback with `false` if exec() fails.

``` javascript
exports.isAvailable = function (callback, scope) {
    var fn = this.createCallbackFn(callback, scope);

    exec(fn, function () { fn(false); }, 'EmailComposer', 'isAvailable', []);
};
```

cordova 5.3.3
cordova-plugin-email 1.0.0

**Comment by hypery2k** [comment]
can you try it with the latest master?

**Comment by resident-uhlig** [comment]
Unfortunately I changed to another plugin so I couldn't try in the real project. However I can confirm that it works in a fresh cordova project:

In the browser the callback is called with the first argument being `false`.
On android (emulator) the callback is called with the first argument being `true`.

Thank you for the update!
