### ISSUE TITLE
Tag for version 1.2.1 points to wrong commit

### ISSUE THREAD

**Issue by MathiasTim** [hypery2k/cordova-email-plugin#30]
I just installed 1.2.1 through npm with 
```
$ cordova plugin add cordova-plugin-email --save
```
and got in `config.xml`.
```
<plugin name="cordova-plugin-email" spec="~1.2.1">
```
But when I started my app and used `open` nothing happened. I debugged the app and found out, that the fix you added in [this commit](https://github.com/hypery2k/cordova-email-plugin/commit/8cd3df60f8ef804d0d05a066ea563bc79ce00d85) was not in my plugin code.

Therefore I checked the repository tagging and saw that the [master](https://github.com/hypery2k/cordova-email-plugin/blob/master/src/ios/APPEmailComposer.m#L94) compared to the [tag 1.2.1](https://github.com/hypery2k/cordova-email-plugin/blob/v1.2.1/src/ios/APPEmailComposer.m#L95) has this small but important difference.

I think this an issue between the github *release* and the repository tag. Npm uses the repository tag and therefore is getting the *old* version, as I did.

There is a workaround for everyone else running into this. Just use the commit hash in `config.xml` until this is fixed:
```
<plugin name="cordova-plugin-email" spec="https://github.com/hypery2k/cordova-email-plugin.git#01596a9bec04d92f5ebfffd1e72cca486bfd94e4" />
```

Keep up the good work!

**Comment by hypery2k** [comment]
I published a new version: https://github.com/hypery2k/cordova-email-plugin/releases/tag/v1.2.2
