### ISSUE TITLE
isAvailable always return empty string on Android

### ISSUE THREAD

**Issue by waybackrider** [hypery2k/cordova-email-plugin#39]
As already mentioned in #29, isAvailable is not working on Android

**Comment by hypery2k** [comment]
which cordova and android version are you using? Which plugin version you're using?

**Comment by waybackrider** [comment]
Hi,

i'm using Cordova 6.4.0 Android platform 6.1.0 and plugin version 1.2.4.
i see there is already a version 1.2.5 but as only version issue was corrected i did not test this version.

**Comment by hypery2k** [comment]
Verified it with cordova 6.4.0, cordovan-android 5.1.1 and android 5.0 and it's working

**Comment by waybackrider** [comment]
Latest cordova-android version is 6.1.0.
Is 5.1.1 the maximung supported Version by this plugin?

**Comment by hypery2k** [comment]
no should not be a limit. Don't use any cordova-android 6 specific stuff. @requenaxii According to your [comment](https://github.com/hypery2k/cordova-email-plugin/issues/25#issuecomment-267553215) which cordova-android version you're using?

**Comment by waybackrider** [comment]
@hypery2k does ist work for you when you upgrade to cordova-android 6.1.0?

**Comment by hypery2k** [comment]
I can't update my sample app due to other restrictions

**Comment by waybackrider** [comment]
Just create an new sample app as i did. cordova-android has no global scope.
I would but cannot downgrade to 5.1.1 because of other plugins

**Comment by hypery2k** [comment]
Indeed the issue only exists for cordova-android 6

**Comment by hypery2k** [comment]
fixed with version 1.2.6

**Comment by waybackrider** [comment]
Thx, confirm it works!
