### ISSUE TITLE
Android: html is stripped out of body

### ISSUE THREAD

**Issue by ntclark4** [hypery2k/cordova-email-plugin#44]
I'm testing this plugin with android and everything seems to be working except for html in the body of the email.

I'm using Cordova 6.5.0 with android platform version 6.1.1 and the latest version of the plugin. I'm testing on an android 7.0 device.

I've tested common tags like h1, a, i, b and br. Oddly, br is the only one that works and it properly adds line breaks.

I've tested with the Gmail and Inbox apps.

**Comment by maxpaj** [comment]
I'm seeing the same on my Android device. Trying to send an email with HTML and picking Gmail as the app when the chooser appears.

With this code, the only thing that appears in the email compose is "Link".
```
    let email = {
      to: ['test@example.com'],
      attachments: [],
      body: '<a href="http://www.example.com">Link</a>', 
      isHtml: true
    };

    // Send a text message using default options
    EmailComposer.open(email);
```

**Comment by hypery2k** [comment]
if you read through the [intro](https://github.com/hypery2k/cordova-email-plugin#html-and-css-on-android) you'll notice that for the Gmail App it doesn't work well..

**Comment by ntclark4** [comment]
@hypery2k The into states "most native Mail clients like the standard app or Gmail only support rich formatted text" and says _css_ is not supported well. I am not trying to add any css, but I am attempting to use basic tags like the < b > and < a > tag which the into says _can be used_. It's unfortunate that this doesn't currently work in android. If this really is the case, and there is no longer a way to add links or even bold text in android, it might be worth updating the docs to reflect that.

**Comment by 7tablets** [comment]
I agree. It's best if author updated the document to state that even tags don't reflect styles.
