### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by remotewhiteboard** [hypery2k/cordova-email-plugin#55]
Add it to my ionic 2 project:

```
$ ionic plugin add cordova-plugin-email
$ npm install --save @ionic-native/email-composer
```
 import it fine

`
import { EmailComposer } from '@ionic-native/email-composer';`

add it to the constructor

`private emailComposer: EmailCompose`

And then I get the error:

```
/iphone/Macquarie/gpstracker-master/node_modules/@ionic-native/email-composer/index.js:10
import { Injectable } from '@angular/core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by hypery2k** [comment]
It seems like your setup does not parse typescript files inside node_modules. see here http://stackoverflow.com/questions/36438191/ionic-2-import-and-export-may-appear-only-with-sourcetype-module
