### ISSUE TITLE
No provider for EmailComposer! 

### ISSUE THREAD

**Issue by suthankumar** [hypery2k/cordova-email-plugin#58]
![image](https://cloud.githubusercontent.com/assets/23583275/25060458/c552c3b6-2195-11e7-8c7b-b912e99ecf52.png)

App module.ts
![image](https://cloud.githubusercontent.com/assets/23583275/25060461/d54ad902-2195-11e7-80cf-a7dd6dce188c.png)
![image](https://cloud.githubusercontent.com/assets/23583275/25060465/efa6335a-2195-11e7-97b2-f2de9022d271.png)

Orderprescription Sheet
![image](https://cloud.githubusercontent.com/assets/23583275/25060481/4f170bac-2196-11e7-958c-1d5ddba57579.png)

![image](https://cloud.githubusercontent.com/assets/23583275/25060486/715e7fba-2196-11e7-9644-7af4efa34a5b.png)

This is my code.  Could you able to help me Please?

**Comment by hypery2k** [comment]
seems like you have add EmailComposer to your AppModule providers

**Comment by hypery2k** [comment]
and please if reporting issues, don't use screenshots for code, paste the code as text
