### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by youradds** [hypery2k/cordova-email-plugin#59]
Hi,

I used to use the katzer version of this plugin, but I can't get it to work (and it looks like it was a while since it was last updated!). I'm trying to work out why this won't work for me:

> Uncaught TypeError: undefined is not a function 

I'm calling it with this in config.xml:

`<plugin spec="https://github.com/hypery2k/cordova-email-plugin" source="git" />`

I see the file in the "assets" folder in the APK, so I'm a bit confused as to what I'm doing wrong?

Thanks

Andy

**Comment by hypery2k** [comment]
use release not git directly

**Comment by youradds** [comment]
So how do you do that then? Cos I've tried it all sorts of ways, and everything broke! (either wouldn't build Phonegaps end, or gave a JS error)

**Comment by hypery2k** [comment]
did you tried this? https://github.com/hypery2k/cordova-email-plugin#phonegap-build

**Comment by youradds** [comment]
Yup, and I get:

```
phonegap.js:314 Uncaught TypeError: fn is not a function
    at onAvailable (email_composer.js:101)
    at Object.callbackFromNative (phonegap.js:293)
    at <anonymous>:1:9
```

Calling with:

```
                                             cordova.plugins.email.open({
                                                 to:         'me@site.co.uk', // email addresses for TO field
                                                 subject:    'Competition export file', // subject of the email
                                                 body:       outputString, // email body (for HTML, set isHtml to true)
                                                 isHtml:     false, // indicats if the body is HTML or plain text
                                             });

```

Cheers

Andy

**Comment by youradds** [comment]
This is what I get:

![2017-05-09 at 15-32-40](https://cloud.githubusercontent.com/assets/2000191/25856046/c024f676-34cc-11e7-8169-33e25f9ca2d4.jpg)
