### ISSUE TITLE
Specify email app not working

### ISSUE THREAD

**Issue by manoj529** [hypery2k/cordova-email-plugin#6]
Hi Team,

Specify Email App is not working and skype , Galery vault, Shareit opens in the email apps list.
Tested in android device with below specification :+1: 
 Android Version : 5.0.2
 Device : Lenovo A6000 Plus

Thank you in advance for any help regarding this!
##

**Comment by hypery2k** [comment]
which cordova version are you using?

**Comment by manoj529** [comment]
i'm using cordova 5.2.0 @hypery2k

**Comment by hypery2k** [comment]
so the desired apps is not opening or what's the exact error?

**Comment by manoj529** [comment]
There are two issues in the scenario @hypery2k:
1) When I specify to open with gmail it won't open. I don't see any error in the console nor the gmail app open action on the screen.
2) according to the documentation it should open the list of all email apps on calling the event. But it gives me the list of all non email apps in the list too.
Ex: 

desired list :
GMail
Yahoo mail
Default email apps in mobile

But I'm getting :

Skype
Wechat
Facebook messenger
Gmail
........ Etc

**Comment by hypery2k** [comment]
for the app listing I've created an new issue, see #12 
If I found some time I will investigate on this, but will take some time

**Comment by hypery2k** [comment]
You can try to use the development version (nightly build), which maybe **not stable!**:

```
cordova plugin add cordova-plugin-email@next
```

**Comment by manoj529** [comment]
Hey thank you for the responce hypery2k. Somehow i managed to use other plugin to solve this issue in develop env back then. I will try to use the plugin if got a chanse and add my feedback about it.

**Comment by xahid09** [comment]
Hi @manoj529, can you please tell me which other plugin you have used?
