### ISSUE TITLE
android.permission.GET_ACCOUNTS permission

### ISSUE THREAD

**Issue by pliablepixels** [hypery2k/cordova-email-plugin#67]
Hi, thanks for this plugin. As of today, it requires android.permission.GET_ACCOUNTS which is an intrusive permission and many users of my app are uncomfortable with it. Is there a way to configure this in a way that it doesn't need this permission?

**Comment by markdon** [comment]
There sure is. The requirement for this permission was removed with [this change](https://github.com/hypery2k/cordova-email-plugin/commit/f9462c2f66d5db0da73a9c1ffabf342e6c13a6d6#diff-1914e64ebaebcb6f845b7e59c24df370R592) but the permission was left in AndroidManifest.xml. I actually ran across this same problem and fixed it for myself ages ago.  You can use [my fork](https://github.com/markdon/cordova-email-plugin) or wait for this [pull request](https://github.com/hypery2k/cordova-email-plugin/pull/69).

**Comment by pliablepixels** [comment]
great thanks - looks like it just got merged too!
