### ISSUE TITLE
WP8.1 - Attachment [Feature/Bug]

### ISSUE THREAD

**Issue by graphefruit** [hypery2k/cordova-email-plugin#8]
Hello!
Is it possible to attach an file on Windows Phone 8.1?
In Android this works (tested already).
I've tested it on Windows Phone 8.1 but it doesn't attach the file.
(The changelog says its possible?)

The attachment on my side looks like: 

```
var attachments = [];
var utf8_to_b64 = function (str) {
    return window.btoa(unescape(encodeURIComponent(str)));
};
var data = "base64:attachmentfile.html//" + utf8_to_b64(content);

attachments.push(data);

cordova.plugins.email.open({
        to: [], // email addresses for TO field
        cc: [], // email addresses for CC field
        bcc: [], // email addresses for BCC field
        attachments: attachments,
        subject: "Subject"
        body: "", // email body (for HTML, set isHtml to true)
        isHtml: false, // indicats if the body is HTML or plain text
    },
    function () {

    });
```

Any idea?

The E-Mail opens and the subject exists, but the attachment isn't available.

Greetings & Thanks
Graphefruit

**Comment by hypery2k** [comment]
It's a known limitation on WP8, see https://github.com/hypery2k/cordova-email-plugin#html-css-and-attachments-on-windows-phone-8

**Comment by graphefruit** [comment]
But on 0.8.2 changes: [enhancement:] Support attachments on Windows Phone 8.1
I'm using 8.1?

**Comment by hypery2k** [comment]
mmmh you're right. Have to look at it

**Comment by graphefruit** [comment]
Thank you!! That would be realy realy awesome for me! :)

**Comment by graphefruit** [comment]
Hello @hypery2k had you already some time to dig into?

Thanks in advance
Graphefruit

**Comment by hypery2k** [comment]
sorry, but I didn't get any windows phone 8 device for testing. Cannot really investigate on this. But will try to work on the Win10 support

**Comment by graphefruit** [comment]
@hypery2k I would have an WP8 phone, maybe I could test it for you? Or maybe a simulator
