### ISSUE TITLE
GET_ACCOUNTS Fix Publish

### ISSUE THREAD

**Issue by payneBrandon** [hypery2k/cordova-email-plugin#80]
Hey,

Just wanted to see if there was a plan to publish the latest fix with the get_accounts permission out to NPM.  The fix is in the latest code as of 8 months ago but the NPM package hasn't been published in a year, and I'd like to avoid pointing to the dev build for stability reasons.

Thanks!

**Comment by hypery2k** [comment]
1.2.7 is published

**Comment by payneBrandon** [comment]
Awesome, up and running. Thank you!
